# Generated by Django 4.1.5 on 2023-02-05 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='t_f_name', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(db_column='t_l_name', max_length=50, verbose_name='Last name')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('salary', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]